import type { Board, Memory, PersistedState } from './types';
import * as art from './art';

let z = 1;

type Seed = Partial<Memory> & Pick<Memory, 'boardId' | 'type' | 'x' | 'y' | 'w' | 'h'>;

const mk = (id: string, s: Seed): Memory => ({
  id,
  title: '',
  caption: '',
  date: '',
  location: '',
  tags: [],
  frameStyle: 'print',
  pinStyle: 'red',
  rotation: 0,
  scale: 1,
  zIndex: z++,
  favorite: false,
  createdAt: Date.now() - 86_400_000 * (40 - z),
  updatedAt: Date.now(),
  ...s,
});

export function buildSeedState(): PersistedState {
  const now = Date.now();

  const boards: Board[] = [
    {
      id: 'b_life',
      name: 'Life',
      description: 'The everything board',
      accent: '#bd4f3c',
      createdAt: now - 86_400_000 * 120,
    },
    {
      id: 'b_travel',
      name: 'Travel',
      description: 'Roads, coasts and long drives',
      accent: '#5f7f99',
      createdAt: now - 86_400_000 * 90,
    },
    {
      id: 'b_friends',
      name: 'Friends',
      description: 'The people who show up',
      accent: '#879a77',
      createdAt: now - 86_400_000 * 60,
    },
    {
      id: 'b_2026',
      name: '2026',
      description: 'This year, as it happens',
      accent: '#e5bd63',
      createdAt: now - 86_400_000 * 30,
    },
  ];

  const memories: Memory[] = [
    /* ---------------------------------------------------------- Life */
    mk('m_beach', {
      boardId: 'b_life',
      type: 'photo',
      imageUrl: art.beach(),
      title: 'First swim of the year',
      caption: 'the water was freezing',
      date: '2026-05-16',
      location: 'Nagsasa Cove',
      tags: ['summer', 'beach', 'friends'],
      frameStyle: 'polaroid',
      pinStyle: 'red',
      x: 800,
      y: 462,
      w: 330,
      h: 235,
      rotation: -4.2,
      favorite: true,
    }),
    mk('m_concert', {
      boardId: 'b_life',
      type: 'photo',
      imageUrl: art.concert(),
      title: 'Front row, somehow',
      caption: 'we lost our voices',
      date: '2026-07-12',
      location: 'Manila',
      tags: ['concert', 'night', 'music'],
      frameStyle: 'noir',
      pinStyle: 'metal',
      x: 1176,
      y: 486,
      w: 356,
      h: 253,
      rotation: 2.6,
    }),
    mk('m_strip', {
      boardId: 'b_life',
      type: 'strip',
      imageUrl: art.photobooth(),
      title: 'Photobooth',
      caption: 'four seconds each',
      date: '2026-07-12',
      location: 'The arcade',
      tags: ['photobooth', 'friends'],
      frameStyle: 'strip',
      pinStyle: 'white',
      x: 1570,
      y: 452,
      w: 168,
      h: 526,
      rotation: -1.8,
      favorite: true,
    }),
    mk('m_friends', {
      boardId: 'b_life',
      type: 'photo',
      imageUrl: art.friends(),
      title: 'Kitchen, 2am',
      caption: 'nobody wanted to go home',
      date: '2026-06-28',
      location: 'Ellie’s place',
      tags: ['friends', 'late nights'],
      frameStyle: 'print',
      pinStyle: 'yellow',
      x: 1806,
      y: 452,
      w: 326,
      h: 254,
      rotation: 3.1,
    }),
    mk('m_sunset', {
      boardId: 'b_life',
      type: 'photo',
      imageUrl: art.sunset(),
      title: 'The good sunset',
      caption: 'we stayed until it was gone',
      date: '2026-04-03',
      location: 'Batangas',
      tags: ['sunset', 'travel'],
      frameStyle: 'vintage',
      pinStyle: 'blue',
      x: 1820,
      y: 790,
      w: 320,
      h: 228,
      rotation: -3.4,
      favorite: true,
    }),
    mk('m_note1', {
      boardId: 'b_life',
      type: 'note',
      text: 'we stayed until\nthe sun gave up',
      date: '2026-04-03',
      x: 1836,
      y: 1008,
      w: 240,
      h: 120,
      rotation: 2.4,
      pinStyle: 'tape',
      tags: ['note'],
    }),
    mk('m_coffee', {
      boardId: 'b_life',
      type: 'photo',
      imageUrl: art.coffee(),
      title: 'Slow Tuesday',
      caption: 'third cup, no regrets',
      date: '2026-03-10',
      location: 'Kalsada Coffee',
      tags: ['coffee', 'quiet'],
      frameStyle: 'modern',
      pinStyle: 'pastel',
      x: 806,
      y: 838,
      w: 292,
      h: 292,
      rotation: 2.2,
    }),
    mk('m_ticket', {
      boardId: 'b_life',
      type: 'ticket',
      title: 'Ticket stub',
      text: 'CONCERT',
      date: '2026-07-12',
      location: 'MANILA',
      tags: ['concert', 'ticket'],
      pinStyle: 'none',
      x: 1186,
      y: 812,
      w: 300,
      h: 132,
      rotation: -5.6,
    }),
    mk('m_sticky', {
      boardId: 'b_life',
      type: 'sticky',
      text: 'remember this day :)',
      color: 'butter',
      date: '2026-07-13',
      x: 1546,
      y: 1062,
      w: 200,
      h: 200,
      rotation: 4.4,
      pinStyle: 'none',
      tags: ['note'],
    }),
    mk('m_postcard', {
      boardId: 'b_life',
      type: 'postcard',
      imageUrl: art.postcardArt(),
      title: 'Postcard from up north',
      caption: 'wish you were here — really',
      text: 'the air is thinner\nand everything is slower.\nsee you in a week.',
      date: '2026-02-18',
      location: 'Sagada',
      tags: ['travel', 'postcard'],
      pinStyle: 'red',
      x: 1830,
      y: 1168,
      w: 340,
      h: 224,
      rotation: 3.2,
    }),
    mk('m_road', {
      boardId: 'b_life',
      type: 'photo',
      imageUrl: art.roadtrip(),
      title: 'Nine hours of nothing',
      caption: 'best playlist ever made',
      date: '2026-01-27',
      location: 'Ilocos highway',
      tags: ['travel', 'roadtrip'],
      frameStyle: 'scrapbook',
      pinStyle: 'glass',
      x: 1150,
      y: 1000,
      w: 320,
      h: 220,
      rotation: -2.2,
    }),
    mk('m_label', {
      boardId: 'b_life',
      type: 'label',
      text: "SUMMER '26",
      x: 836,
      y: 1188,
      w: 214,
      h: 58,
      rotation: -7.5,
      pinStyle: 'none',
      tags: ['label'],
    }),
    mk('m_bloom', {
      boardId: 'b_life',
      type: 'memorabilia',
      imageUrl: art.bloom(),
      title: 'Pressed in a book',
      caption: 'from the garden',
      date: '2026-05-02',
      tags: ['keepsake'],
      frameStyle: 'modern',
      pinStyle: 'white',
      x: 1430,
      y: 1180,
      w: 140,
      h: 140,
      rotation: 6.5,
    }),
    mk('m_note2', {
      boardId: 'b_life',
      type: 'note',
      text: 'call mom on\nsunday!!',
      x: 1490,
      y: 1298,
      w: 210,
      h: 110,
      rotation: -3.6,
      pinStyle: 'blue',
      tags: ['note'],
    }),

    /* -------------------------------------------------------- Travel */
    mk('m_t_road', {
      boardId: 'b_travel',
      type: 'photo',
      imageUrl: art.roadtrip(),
      title: 'The long way round',
      caption: 'no signal for six hours',
      date: '2026-01-27',
      location: 'Ilocos highway',
      tags: ['roadtrip', 'drive'],
      frameStyle: 'polaroid',
      pinStyle: 'red',
      x: 1240,
      y: 700,
      w: 340,
      h: 234,
      rotation: -3.0,
    }),
    mk('m_t_post', {
      boardId: 'b_travel',
      type: 'postcard',
      imageUrl: art.postcardArt(),
      title: 'Sagada',
      caption: 'cold mornings, warm coffee',
      text: 'the air is thinner\nand everything is slower.',
      date: '2026-02-18',
      location: 'Sagada',
      tags: ['postcard', 'mountains'],
      pinStyle: 'metal',
      x: 1700,
      y: 730,
      w: 340,
      h: 224,
      rotation: 2.6,
    }),
    mk('m_t_sun', {
      boardId: 'b_travel',
      type: 'photo',
      imageUrl: art.sunset(),
      title: 'Ferry home',
      caption: '',
      date: '2026-04-03',
      location: 'Batangas',
      tags: ['sunset', 'sea'],
      frameStyle: 'vintage',
      pinStyle: 'blue',
      x: 1330,
      y: 1030,
      w: 320,
      h: 228,
      rotation: 3.4,
      favorite: true,
    }),
    mk('m_t_label', {
      boardId: 'b_travel',
      type: 'label',
      text: 'GOING PLACES',
      x: 1770,
      y: 1050,
      w: 232,
      h: 58,
      rotation: -5.0,
      pinStyle: 'none',
    }),
  ];

  return {
    version: 1,
    boards,
    memories,
    activeBoardId: 'b_life',
  };
}
